{
 "title": "Mini-RaftKV",
 "refresh": "5s",
 "panels": [
  {
   "title": "Committed Entries",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(raftkv_committed_entries_total[1m])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Applied Entries",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(raftkv_applied_entries_total[1m])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Role Changes",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(raftkv_role_changes_total[5m])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Replication Errors",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(raftkv_replication_errors_total[1m])",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}