id: n3
addr: 127.0.0.1:7003
metrics_addr: 127.0.0.1:9003
data_path: data/n3.db
election_ticks: 14
election_jitter_ticks: 10
heartbeat_ticks: 2
snapshot_threshold: 1024
peers:
  n1: 127.0.0.1:7001
  n2: 127.0.0.1:7002
